### ISSUE TITLE
rails 6 support?

### ISSUE THREAD

**Issue by nir0** [mainio/ratonvirus#7]
i have this error:

```
rails (~> 6.0) was resolved to 6.0.1.rc1, which depends
on
      activestorage (= 6.0.1.rc1)

Bundler could not find compatible versions for gem
"activesupport":
  In Gemfile:
rails (~> 6.0) was resolved to 6.0.1.rc1, which depends
on
      activesupport (= 6.0.1.rc1)

    ratonvirus-clamby was resolved to 0.1.0, which depends on
ratonvirus (~> 0.1.0) was resolved to 0.1.1, which
depends on
        activesupport (~> 5.0)
```

**Comment by retsef** [comment]
i have recently made a pull request (#6) to upgrade the compatibility with rails 6 on the gemspec level.
You must use, at the moment, the master branch with `gem 'ratonvirus', github: 'mainio/ratonvirus'` until @ahukkanen will bump the update to rubygems

**Comment by nir0** [comment]
@retsef thank you very much!

**Comment by ahukkanen** [comment]
@retsef Will do the release as soon as I have time to check the test suite is running without errors on Rails 6. I was planning initially to do it directly after merging your PR but I bumped into some errors with the dummy app.

**Comment by ahukkanen** [comment]
There is now a new `0.2.0` release with Rails 6 support available at RubyGems.

I have reverted the version number changes in the gemspec from @retsef because the previous version did not **really** work with Rails 6 because it has changed how ActiveStorage works.

- If you've been running on Rails 6 with the previous git version and CarrierWave, you are perfectly fine.
- If you've been running on Rails 6 with the previous git version and ActiveStorage, your virus checks have not worked if you rely on the validator provided by Ratonvirus. This might have gone off the radar because the failure happens in a silent way, Ratonvirus cannot access those files and therefore it couldn't scan them either.

The new `0.2.0` version is a partial rewrite of the ActiveStorage storage engine support in Ratonvirus and works with Rails 6 + ActiveStorage.

Because of this, I also decided to lock Ratonvirus `0.1.x` with Rails 5 and Ratonvirus `0.2.x` (or future versions) with Rails 6. ActiveStorage is still a relatively new feature in Rails which can lead to API changes that can also affect Ratonvirus.

For all Rails 6 users out there:
**Please update Ratonvirus to `0.2.0`**
